#!/bin/bash

gcc -o blinker blinker.c -l wiringPi -l pthread
gcc -o i2cprobe i2cprobe.c -l wiringPi -l pthread
gcc -o bt_test bt_test.c -l bluetooth
gcc -o test test.c -l wiringPi -l pthread -l bluetooth
